TRAIN:
  ENABLE: True
  DATASET: mp
  BATCH_SIZE: 10
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /home/ashish/Projects/pretrained/R2PLUS1D_16x4_R50.pyth
  CHECKPOINT_INFLATE: True
  CHECKPOINT_EPOCH_RESET: True
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /home/ashish/Results/Datasets/HPE2/FrameToVideos
  PATH_PREFIX: /home/ashish/Results/Datasets/HPE2/FrameToVideos/MP
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  DEPTH: 50
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1 # 1-node
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 0.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 4
  ARCH: r2plus1d
  MODEL_NAME: PTVR2plus1D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  SINGLE_PATHWAY_ARCH: ['r2plus1d']
TEST:
  ENABLE: True
  DATASET: mp
  BATCH_SIZE: 20
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
